#include"main.h"
/**
*cap_string-capitalizefirstletterofeachword
*@s:stringtomanipulate
*Return:string
*/
char*cap_string(char*s)
{
	inti;
	
	/*checkfirstindexforupper-case*/
	if(s[0]>=97&&s[0]<=122)
		s[0]-=32;
	/*iflowercaseandpriorcharisseparator,capitalize*/
	for(i=0;s[i]!='\0';i++)
	{
		if((s[i]>=97&&s[i]<=122)
		&&(s[i-1]==','||s[i-1]==';'||s[i-1]=='.'||
			s[i-1]=='!'||s[i-1]=='?'||s[i-1]=='"'||
			s[i-1]=='('||s[i-1]==')'||s[i-1]=='{'||
			s[i-1]=='}'||s[i-1]==''||s[i-1]=='\t'
			||s[i-1]=='\n'))
			s[i]-=32;
	}
	return(s);
}
